-- Create a narrow table that matches data/scorecard_subset.csv
CREATE TABLE dbo.Scorecard (
  UNITID INT PRIMARY KEY,
  INSTNM NVARCHAR(256),
  STABBR CHAR(2),
  CONTROL NVARCHAR(30),
  PREDDEG NVARCHAR(30),
  LOCALE INT NULL,
  UGDS INT NULL,
  RETENTION_FT_4YR DECIMAL(5,2) NULL,
  RETENTION_PT_4YR DECIMAL(5,2) NULL,
  RETENTION_FT_2YR DECIMAL(5,2) NULL,
  RETENTION_PT_2YR DECIMAL(5,2) NULL,
  COMPLETION_150_4YR DECIMAL(5,2) NULL,
  COMPLETION_150_2YR DECIMAL(5,2) NULL,
  TUITIONFEE_IN INT NULL,
  PELL_SHARE DECIMAL(5,2) NULL
);
